'use client';

import React from 'react';
import ProjectTemplate from '../../../components/ProjectTemplate';

export default function RegulationsGovTool() {
  const media = [
    {
      src: "https://www.youtube.com/watch?v=8r_MLLDKaQ0",
      caption: "Regulations.gov Tool Demo Video - AI-powered civic engagement platform for matching user profiles with regulatory documents",
      type: "youtube" as const,
      alt: "Regulations.gov Tool Demo Video"
    }
  ];

  const overview = `Built a desktop application that enables users to search, track, and discover government documents with personalized recommendations and sentiment analysis. Refined through feedback from activists and government teachers to improve civic participation while protecting user data through local processing. The platform features AI-powered document analysis, sentiment analysis of comment boards, and interactive force-directed graph visualizations.

Developed using Tauri (Rust + React/TypeScript) with a comprehensive backend infrastructure including Express.js HTTP server, SQLite relational database, and Qdrant vector database. The system includes automated Docker-containerized document pipelines with N8N, local RAG implementation with Ollama inference, and advanced visualization tools for exploring regulatory document relationships. Winner of Hack4Humanity and Hacktivism hackathon.`;

  const bulletPoints = [
    "Built desktop app enabling users to search, track, and discover government documents with personalized recommendations and sentiment analysis, refined through feedback from activists and government teacher",
    "Ensured 100% data privacy with local processing using Tauri (Rust + React/TypeScript) and Ollama inference",
    "Developed Docker-containerized workflow with N8N and regulations.gov APIs to fetch 1000+ documents weekly into Supabase",
    "Implemented local RAG system with Express.js, SQLite, and Qdrant for document chunking and user-profile matching, displaying matches with thumbnails generated by Gemini",
    "Engineered force-directed graph matching algorithm achieving 95% accuracy by modeling documents and user interests as nodes with semantic similarity scores as attractive forces"
  ];

  return (
    <ProjectTemplate
      title="Regulations.gov Tool"
      media={media}
      overview={overview}
      bulletPoints={bulletPoints}
    />
  );
}
